In [1]:
import keras
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score as accsc
from sklearn.impute import SimpleImputer as Imp
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder 
import time

In [2]:
df = pd.read_csv("BankChurners.csv")

In [3]:
df = df.iloc[:, :21]

In [4]:
y = df['Attrition_Flag'].values
x = df.drop(['Attrition_Flag', 'CLIENTNUM' ], axis=1)

In [5]:
labely = LabelEncoder()

In [6]:
y = labely.fit_transform(y)

In [7]:
labelx = LabelEncoder()
labels = ['Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']  
for label in labels:
    labelenc = LabelEncoder()
    x[label] = labelenc.fit_transform(x[label])

In [8]:
x.head(20)

,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,45,1,3,3,1,2,0,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,49,0,5,2,2,4,0,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,51,1,3,2,1,3,0,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,40,0,4,3,3,4,0,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,40,1,3,5,1,2,0,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
5,44,1,2,2,1,1,0,36,3,1,2,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311
6,51,1,4,6,1,0,1,46,6,1,3,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066
7,32,1,0,3,3,2,3,27,2,2,2,29081.0,1396,27685.0,2.204,1538,36,0.714,0.048
8,37,1,3,5,2,2,0,36,5,2,0,22352.0,2517,19835.0,3.355,1350,24,1.182,0.113
9,48,1,2,2,2,3,0,36,6,3,3,11656.0,1677,9979.0,1.524,1441,32,0.882,0.144
10,42,1,5,5,3,0,0,31,5,3,2,6748.0,1467,5281.0,0.831,1201,42,0.680,0.217
11,65,1,1,6,1,1,0,54,6,2,3,9095.0,1587,7508.0,1.433,1314,26,1.364,0.174
12,56,1,1,0,2,3,0,36,3,6,0,11751.0,0,11751.0,3.397,1539,17,3.250,0.000
13,35,1,3,2,3,2,0,30,5,1,3,8547.0,1666,6881.0,1.163,1311,33,2.000,0.195
14,57,0,2,2,1,4,0,48,5,2,2,2436.0,680,1756.0,1.190,1570,29,0.611,0.279
15,44,1,4,6,3,3,0,37,5,1,2,4234.0,972,3262.0,1.707,1348,27,1.700,0.230
16,48,1,4,4,2,3,0,36,6,2,3,30367.0,2362,28005.0,1.708,1671,27,0.929,0.078
17,41,1,3,6,1,3,0,34,4,4,1,13535.0,1291,12244.0,0.653,1028,21,1.625,0.095
18,61,1,1,3,1,1,0,56,2,2,3,3193.0,2517,676.0,1.831,1336,30,1.143,0.788
19,45,0,2,2,1,5,0,37,6,1,2,14470.0,1157,13313.0,0.966,1207,21,0.909,0.080

In [9]:
# data = x[labels]

In [10]:
# for label in labels:
#     ohenc = OneHotEncoder()
#     data += ohenc.fit_transform(data[label])


# #enc.fit_transform(bridge_df[['Bridge_Types_Cat']])

In [11]:
xtrain, xtest, ytrain, ytest = tts(x, y, test_size = 0.3, random_state = 8)

In [12]:
scaler = StandardScaler()

In [13]:
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [14]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

model = Sequential()
model.add(Dense(19, input_dim = 19, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(19, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss= 'mae', optimizer='adam', metrics=['accuracy'])

In [15]:
start = time.time()
model.fit(xtrain, ytrain, epochs=100, batch_size = 20)

Epoch 1/100
355/355 [==============================] - 0s 860us/step - loss: 0.2699 - accuracy: 0.7854
Epoch 2/100
355/355 [==============================] - 0s 939us/step - loss: 0.1729 - accuracy: 0.8380
Epoch 3/100
355/355 [==============================] - 0s 902us/step - loss: 0.1651 - accuracy: 0.8387
Epoch 4/100
355/355 [==============================] - 0s 857us/step - loss: 0.1630 - accuracy: 0.8392
Epoch 5/100
355/355 [==============================] - 0s 849us/step - loss: 0.1622 - accuracy: 0.8389
Epoch 6/100
355/355 [==============================] - 0s 916us/step - loss: 0.1616 - accuracy: 0.8392
Epoch 7/100
355/355 [==============================] - 0s 902us/step - loss: 0.1613 - accuracy: 0.8392
Epoch 8/100
355/355 [==============================] - 0s 879us/step - loss: 0.1594 - accuracy: 0.8402
Epoch 9/100
355/355 [==============================] - 0s 992us/step - loss: 0.1463 - accuracy: 0.8547
Epoch 10/100
355/355 [==============================] - 0s 1ms/step - loss: 0.1424 - accuracy: 0.8584
Epoch 11/100
355/355 [==============================] - 0s 1ms/step - loss: 0.1348 - accuracy: 0.8663
Epoch 12/100
355/355 [==============================] - 0s 950us/step - loss: 0.1332 - accuracy: 0.8665
Epoch 13/100
355/355 [==============================] - 0s 902us/step - loss: 0.1281 - accuracy: 0.8729
Epoch 14/100
355/355 [==============================] - 0s 969us/step - loss: 0.1263 - accuracy: 0.8736
Epoch 15/100
355/355 [==============================] - 0s 913us/step - loss: 0.1226 - accuracy: 0.8774
Epoch 16/100
355/355 [==============================] - 0s 1ms/step - loss: 0.1195 - accuracy: 0.8797
Epoch 17/100
355/355 [==============================] - 0s 1ms/step - loss: 0.1245 - accuracy: 0.8775
Epoch 18/100
355/355 [==============================] - 0s 1ms/step - loss: 0.1208 - accuracy: 0.8815
Epoch 19/100
355/355 [==============================] - 0s 1ms/step - loss: 0.1190 - accuracy: 0.8823
Epoch 20/100
355/355 [==============================] - 0s 939us/step - loss: 0.1157 - accuracy: 0.8869
Epoch 21/100
355/355 [==============================] - 1s 1ms/step - loss: 0.1176 - accuracy: 0.8839
Epoch 22/100
355/355 [==============================] - 0s 1ms/step - loss: 0.1162 - accuracy: 0.8852
Epoch 23/100
355/355 [==============================] - 0s 958us/step - loss: 0.1143 - accuracy: 0.8871
Epoch 24/100
355/355 [==============================] - 0s 965us/step - loss: 0.1128 - accuracy: 0.8887
Epoch 25/100
355/355 [==============================] - 0s 857us/step - loss: 0.1114 - accuracy: 0.8900
Epoch 26/100
355/355 [==============================] - 0s 890us/step - loss: 0.1134 - accuracy: 0.8864
Epoch 27/100
355/355 [==============================] - 0s 902us/step - loss: 0.1068 - accuracy: 0.8928
Epoch 28/100
355/355 [==============================] - 0s 885us/step - loss: 0.1089 - accuracy: 0.8949
Epoch 29/100
355/355 [==============================] - 0s 857us/step - loss: 0.1063 - accuracy: 0.8998
Epoch 30/100
355/355 [==============================] - 0s 861us/step - loss: 0.1004 - accuracy: 0.9048
Epoch 31/100
355/355 [==============================] - 0s 860us/step - loss: 0.1018 - accuracy: 0.9043
Epoch 32/100
355/355 [==============================] - 0s 894us/step - loss: 0.0977 - accuracy: 0.9076
Epoch 33/100
355/355 [==============================] - 0s 848us/step - loss: 0.0988 - accuracy: 0.9062
Epoch 34/100
355/355 [==============================] - 0s 913us/step - loss: 0.0975 - accuracy: 0.9073
Epoch 35/100
355/355 [==============================] - 0s 868us/step - loss: 0.0963 - accuracy: 0.9069
Epoch 36/100
355/355 [==============================] - 0s 860us/step - loss: 0.0943 - accuracy: 0.9094
Epoch 37/100
355/355 [==============================] - 0s 837us/step - loss: 0.0919 - accuracy: 0.9115
Epoch 38/100
355/355 [==============================] - 0s 857us/step - loss: 0.0931 - accuracy: 0.9101
Epoch 39/100
355/355 [==============================] - 0s 981us/step - loss: 0.0914 - accuracy: 0.9118
Epoch 40/100
355/355 [==============================] - 0s 951us/step - loss: 0.0940 - accuracy: 0.9080
Epoch 41/100
355/355 [==============================] - 0s 916us/step - loss: 0.0913 - accuracy: 0.9118
Epoch 42/100
355/355 [==============================] - 0s 981us/step - loss: 0.0903 - accuracy: 0.9118
Epoch 43/100
355/355 [==============================] - 0s 890us/step - loss: 0.0922 - accuracy: 0.9103
Epoch 44/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0909 - accuracy: 0.9107
Epoch 45/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0909 - accuracy: 0.9113
Epoch 46/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0886 - accuracy: 0.9137
Epoch 47/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0900 - accuracy: 0.9128
Epoch 48/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0867 - accuracy: 0.9159
Epoch 49/100
355/355 [==============================] - 0s 893us/step - loss: 0.0855 - accuracy: 0.9169
Epoch 50/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0850 - accuracy: 0.9166
Epoch 51/100
355/355 [==============================] - 0s 996us/step - loss: 0.0890 - accuracy: 0.9122
Epoch 52/100
355/355 [==============================] - 0s 905us/step - loss: 0.0858 - accuracy: 0.9159
Epoch 53/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0889 - accuracy: 0.9122
Epoch 54/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0879 - accuracy: 0.9141
Epoch 55/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0889 - accuracy: 0.9127
Epoch 56/100
355/355 [==============================] - 0s 902us/step - loss: 0.0865 - accuracy: 0.9144
Epoch 57/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0864 - accuracy: 0.9153
Epoch 58/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0862 - accuracy: 0.9155
Epoch 59/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0839 - accuracy: 0.9185
Epoch 60/100
355/355 [==============================] - 0s 902us/step - loss: 0.0882 - accuracy: 0.9128
Epoch 61/100
355/355 [==============================] - 0s 924us/step - loss: 0.0855 - accuracy: 0.9155
Epoch 62/100
355/355 [==============================] - 0s 995us/step - loss: 0.0852 - accuracy: 0.9152
Epoch 63/100
355/355 [==============================] - 0s 950us/step - loss: 0.0849 - accuracy: 0.9163
Epoch 64/100
355/355 [==============================] - 0s 958us/step - loss: 0.0842 - accuracy: 0.9176
Epoch 65/100
355/355 [==============================] - 0s 955us/step - loss: 0.0837 - accuracy: 0.9175
Epoch 66/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0834 - accuracy: 0.9183
Epoch 67/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0849 - accuracy: 0.9162
Epoch 68/100
355/355 [==============================] - 0s 931us/step - loss: 0.0839 - accuracy: 0.9172
Epoch 69/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0832 - accuracy: 0.9185
Epoch 70/100
355/355 [==============================] - 0s 947us/step - loss: 0.0797 - accuracy: 0.9216
Epoch 71/100
355/355 [==============================] - 0s 906us/step - loss: 0.0815 - accuracy: 0.9194
Epoch 72/100
355/355 [==============================] - 0s 893us/step - loss: 0.0847 - accuracy: 0.9169
Epoch 73/100
355/355 [==============================] - 0s 913us/step - loss: 0.0850 - accuracy: 0.9163
Epoch 74/100
355/355 [==============================] - 0s 872us/step - loss: 0.0836 - accuracy: 0.9175
Epoch 75/100
355/355 [==============================] - 0s 894us/step - loss: 0.0832 - accuracy: 0.9177
Epoch 76/100
355/355 [==============================] - 0s 879us/step - loss: 0.0798 - accuracy: 0.9210
Epoch 77/100
355/355 [==============================] - 0s 902us/step - loss: 0.0788 - accuracy: 0.9223
Epoch 78/100
355/355 [==============================] - 0s 845us/step - loss: 0.0826 - accuracy: 0.9186
Epoch 79/100
355/355 [==============================] - 0s 902us/step - loss: 0.0819 - accuracy: 0.9200
Epoch 80/100

355/355 [==============================] - 0s 879us/step - loss: 0.0800 - accuracy: 0.9213
Epoch 81/100
355/355 [==============================] - 0s 845us/step - loss: 0.0802 - accuracy: 0.9211
Epoch 82/100
355/355 [==============================] - 0s 871us/step - loss: 0.0818 - accuracy: 0.9189
Epoch 83/100
355/355 [==============================] - 0s 856us/step - loss: 0.0803 - accuracy: 0.9209
Epoch 84/100
355/355 [==============================] - 0s 860us/step - loss: 0.0810 - accuracy: 0.9206
Epoch 85/100
355/355 [==============================] - 0s 1ms/step - loss: 0.0804 - accuracy: 0.9209
Epoch 86/100
355/355 [==============================] - 0s 857us/step - loss: 0.0819 - accuracy: 0.9192
Epoch 87/100
355/355 [==============================] - 0s 839us/step - loss: 0.0799 - accuracy: 0.9204
Epoch 88/100
355/355 [==============================] - 0s 893us/step - loss: 0.0786 - accuracy: 0.9221
Epoch 89/100
355/355 [==============================] - 0s 834us/step - loss: 0.0818 - accuracy: 0.9179
Epoch 90/100
355/355 [==============================] - 0s 868us/step - loss: 0.0822 - accuracy: 0.9183
Epoch 91/100
355/355 [==============================] - 0s 860us/step - loss: 0.0803 - accuracy: 0.9204
Epoch 92/100
355/355 [==============================] - 0s 860us/step - loss: 0.0780 - accuracy: 0.9225
Epoch 93/100
355/355 [==============================] - 0s 902us/step - loss: 0.0799 - accuracy: 0.9213
Epoch 94/100
355/355 [==============================] - 0s 845us/step - loss: 0.0801 - accuracy: 0.9201
Epoch 95/100
355/355 [==============================] - 0s 845us/step - loss: 0.0822 - accuracy: 0.9180
Epoch 96/100
355/355 [==============================] - 0s 852us/step - loss: 0.0788 - accuracy: 0.9223
Epoch 97/100
355/355 [==============================] - 0s 868us/step - loss: 0.0808 - accuracy: 0.9203
Epoch 98/100
355/355 [==============================] - 0s 838us/step - loss: 0.0809 - accuracy: 0.9199
Epoch 99/100
355/355 [==============================] - 0s 905us/step - loss: 0.0814 - accuracy: 0.9193
Epoch 100/100
355/355 [==============================] - 0s 890us/step - loss: 0.0820 - accuracy: 0.9187

In [16]:
accuracy = model.evaluate(xtest, ytest)
end = time.time()
print(end - start)
print(accuracy)

95/95 [==============================] - 0s 926us/step - loss: 0.0785 - accuracy: 0.9223
35.200096130371094
[0.07854177802801132, 0.9223428964614868]

In [17]:
from sklearn.svm import SVC

svc = SVC(kernel = 'linear' )
svc.fit(xtrain, ytrain)
ypredsvc = svc.predict(xtest)

print(accsc(ytest, ypredsvc))

0.9088515959197104

In [18]:

from sklearn.neighbors import KNeighborsClassifier as KNN

knn = KNN(n_neighbors = 11, metric = 'euclidean')
knn.fit(xtrain, ytrain)
ypredknn = knn.predict(xtest)

print(accsc(ytest, ypredknn))

0.9075353734781179

In [19]:
# Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier(n_estimators=100)
clf.fit(xtrain,ytrain)

ypredrfc = clf.predict(xtest)

print(accsc(ytest, ypredrfc))

0.9605133267522211